name: dip_frontend
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.2
  whelm:
    git: https://github.com/fekz115/whelm.git

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  lint: ^1.5.3
  

flutter:
  uses-material-design: true