name: dip_frontend
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  animated_size_and_fade: ^2.0.0
  dio: ^4.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1
  objectdb: ^1.2.1
  path_provider: ^2.0.2
  provider: ^5.0.0
  whelm:
    #git: https://github.com/fekz115/whelm.git
    path: ../whelm

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  lint: ^1.5.3
  

flutter:
  uses-material-design: true